### ISSUE TITLE
🐞 Not using whole GPU

### ISSUE THREAD

**Issue by JFWooten4** [FredericRezeau/fcm-miner#2]
I only see 26% GPU1 utilization (0% GPU2) re [note 1](https://github.com/FredericRezeau/fcm-miner/pull/1) despite tinkering extensively with the `max-threads` and `batch-size` - how can I help? 💭

**Comment by JFWooten4** [comment]
Does these look about right to you? Conf. with the 1070 on PCIE 2 (1060 3GB on v3). Thanks for your help, and shoutout to @overcat for the new free public RPC!

![image](https://github.com/user-attachments/assets/d2d84a20-4105-47c3-a03a-2f8dd64d5834)

**Comment by JFWooten4** [comment]
fixed with the following:

| GPU      | Batch Size | Max Threads |
|----------|------------|-------------|
| GTX 1070 | 5000000    | 512         |
| GTX 1060 | 5000000    | 512         |

Sometimes this is how I learn (via public forum), hope it at least helped in ideating the ingenious 19ff2778bbb6c814b27787f259d16d00f0c7c9c8 patch 💜

**Comment by FredericRezeau** [comment]
Indeed, the miner was only picking up the default device (ordinal 0) before this commit. This should work for both CUDA and OpenCL now. The scripts have also been updated (e.g., `./poll.sh 1` to poll with second device)
